@startuml
== Connecting: authentication and peer identification ==
participant "Node A" as A
participant "Node B" as B
A -> B : TLS handshake\n(self-issued vendor TLS certificate)
activate A
activate B
A -> A: Verify peer certificate
B -> B: Verify peer certificate
note right
   Certificate is verified against
   preconfigured Nuts Foundation
   certificate tree.
end note
B --> A : TLS handshake completed

A -> B : Hello(peerInfo)
note right
   Peer info contains a node's <i>multiaddr</i>
   (as in libp2p) containing all addresses that can
   be used to connect to this node. This allows nodes
   of the same vendor to form a cluster (probably behind a firewall).
end note
B -> B : Add to peerlist
B --> A : (peerInfo)
A -> A : Add to peerlist

== Discovery ==
B -> A : AdvertPeerList(peerlist)
A --> B
A -> A : Connect to new peers
note right
   TODO: Should node B broadcast node A's
   peerInfo to its other peers?
end note
A -> B : AdvertPeerList(peerlist)
B --> A
B -> B : Connect to new peers

== Broadcast ==
A -> B : Broadcast(channel, message)
note right
   we broadcast the message to all of our peers. Since we
   have a full mesh network relaying the message is not necessary.
   Broadcasts at-most-once (no guaranteed delivery).
end note
@enduml